#!/usr/bin/env bash
# tools/new_week_skeleton.sh
# Generate course/week<N>/{lectures,labs,deliverables,assets}/ and stub README.md
# Usage: bash tools/new_week_skeleton.sh <week_number>

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <week_number>" >&2
    exit 2
fi

WEEK="$1"

if ! [[ "$WEEK" =~ ^[0-9]+$ ]]; then
    echo "Error: week number must be a non-negative integer (got: $WEEK)" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$REPO_ROOT/course/week$WEEK"

if [[ -e "$TARGET" ]]; then
    echo "Error: $TARGET already exists. Refusing to overwrite." >&2
    exit 1
fi

mkdir -p "$TARGET/lectures" "$TARGET/labs" "$TARGET/deliverables" "$TARGET/assets"

cat > "$TARGET/README.md" <<EOF
---
type: week
id: W${WEEK}-README
title: Week ${WEEK} (TBD)
week: ${WEEK}
duration_min: 0
prerequisites: []
worldcpj_ct: []
roles: [common]
references: []
deliverables: []
---

# Week ${WEEK}

> **Skeleton** generated by tools/new_week_skeleton.sh on $(date -I).
> Replace this stub before SP commit.

## 目的
TBD

## 合格条件サマリ
- TBD

## Lecture / Lab 一覧
TBD

## 参照
TBD
EOF

echo "Created: $TARGET"
echo "  $TARGET/lectures/"
echo "  $TARGET/labs/"
echo "  $TARGET/deliverables/"
echo "  $TARGET/assets/"
echo "  $TARGET/README.md (stub — fill in before commit)"
